# Generated by Django 2.2.12 on 2020-04-11 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import oscar.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('account_nickname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Account Alias/Nickname')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Last Name')),
                ('books', models.ManyToManyField(blank=True, to='bookstore.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_alias', models.CharField(max_length=100, verbose_name='Distinct Address Name')),
                ('line1', models.CharField(blank=True, max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
