# Generated by Django 3.0.2 on 2020-02-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200216_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
    ]
