# Generated by Django 3.0.5 on 2020-04-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='Nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
    ]
