# Generated by Django 2.2.12 on 2020-04-11 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200411_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Account_Nickname',
            new_name='account_nickname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Middle_Name',
            new_name='middle_name',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_alias', models.CharField(max_length=100, verbose_name='Distinct Address Name')),
                ('line1', models.CharField(blank=True, max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['address_alias'],
            },
        ),
    ]
