# Generated by Django 3.0.5 on 2020-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
        ('users', '0011_auto_20200405_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, to='bookstore.Book'),
        ),
    ]
