# Generated by Django 3.0.5 on 2020-04-10 22:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20200410_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Account_Nickname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Account Alias/Nickname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Middle_Name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='ZIP code'),
        ),
    ]
