# Generated by Django 3.0.3 on 2020-03-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
