# Generated by Django 2.2.12 on 2020-04-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
